config/routes.rb
Rails.application.routes.draw do
  devise_for :customers do
    get "/customers/sign_out" => "devise/sessions#destroy", :as => :destroy_customer_session
  end
  get 'home/About'
  get 'home/Contact'
  get 'cart' => 'cart#show'
  get 'cart/complete'
  post 'cart/add'
  post 'cart/remove'
  post 'cart/update_prices'
  get 'cart/checkout' => 'cart#checkout'
  post 'cart/checkout' => 'cart#checkout'
  get '/products/search'
  get 'categories' => 'categories#index'
  resources :categories
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # resources :characters
  resources :products
  # resources :shipments
   resources :orders
   resources :customers

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
end

app/models/address.rb
class Address < ApplicationRecord
  has_one :province
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :order_products
  has_many :custom_product, through: :order_products

  def total
    order_products.to_a.sum { |order_product| order_product.total }
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, uniqueness: true
end

app/models/character.rb
class Character < ApplicationRecord
  has_many :custom_products

  validates :name, uniqueness: true
end

app/models/custom_product.rb
class CustomProduct < ApplicationRecord
  belongs_to :product
  belongs_to :character
  has_many :order_products
  has_many :carts, through: :order_products

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
  has_one :address

end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  has_one :shipment
  has_one :cart
  has_one :address

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :custom_product
  belongs_to :cart

  def total
    custom_product.price * quantity
  end

  def in_cents
    (custom_product.price * 100).to_i
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :custom_products
  belongs_to :category

  paginates_per 10
end

app/models/province.rb
class Province < ApplicationRecord
end

app/models/shipment.rb
class Shipment < ApplicationRecord
  belongs_to :order

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  require 'date'

  def show
    @render_cart = false
  end

  def update_prices
    @province = Province.find(params[:tax_province])
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [turbo_stream.replace("totals", partial: "cart/total", locals: { province: @province })]
      end
    end
  end

  def add
    new_product_combination = CustomProduct.where(character_id: params[:choice]).where(product_id: params[:id])
    quantity = params[:quantity].to_i
    if params[:commit] == "Update" && quantity.positive?

      current_order_product = OrderProduct.find(params[:order_product_id])
      current_order_product.update(quantity: quantity)
      if current_order_product.custom_product_id != new_product_combination[0].id
        current_order_product.update(custom_product_id: new_product_combination[0].id)
      end

    elsif params[:commit] == "Remove" || quantity < 1

      current_order_product = OrderProduct.find(params[:order_product_id])
      current_order_product.destroy

    elsif params[:commit] == "Add To Cart"

      @cart.order_products.create!(price: new_product_combination[0].price,
                                   custom_product: new_product_combination[0], quantity: quantity)

    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [turbo_stream.replace("cart", partial: "cart/cart", locals: { cart: @cart }),
                              turbo_stream.replace(@product)]
      end
    end
  end

  def remove
    OrderProduct.find_by(id: params[:id]).destroy

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [turbo_stream.replace("cart", partial: "cart/cart",
                                                           locals:  { cart: @cart })]
      end
    end
  end

  def checkout
    @render_cart = false
    cart = @cart;
    checkout_items = Array.new
    cart.order_products.each do |product, index|
      checkout_items << {
        price_data: {
          currency: 'cad',
          unit_amount: product.in_cents,
          product_data: {
            name: product.custom_product.product.name,
            description: product.custom_product.product.description,
          },
          tax_behavior: 'exclusive',
        },
        quantity: product.quantity,
      }
    end
    Stripe.api_key = 'sk_test_51M8YIsImcZ7reNdWFyYDqUvNZFyi2eshDo1EInzxlOhqPO7JDomzCRLLHwcvzGaHX6LuPLuMnAtsNVVuvBbU8ld500R9PEwXHf'
    @order = Order.create(
      order_date: Date.today,
      order_subtotal: @cart.total,
      order_state: "New"
    );

    if customer_signed_in?
      @order.customer_id = current_customer.id
      email = current_customer.email
      if current_customer.address
        @order.address_id = current_customer.address.id
        address_used = true
      end
    end
    if !address_used
      email = nil;
      new_address = Address.create(
        province_id: params[:province],
        city: params[:city],
        line1: params[:line1],
        postal_code: params[:postal_code])

        @order.address_id = new_address.id

      if customer_signed_in?
        current_customer.address = new_address
      end
    end



    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      success_url: cart_complete_url + "?session_id={CHECKOUT_SESSION_ID}&order_id=#{@order.id}",
      line_items: checkout_items,
      cancel_url: cart_url,
      automatic_tax: { enabled: true },
      mode: "payment",
      customer_email: email
    )

    @order.update(
      stripe_id: @session.id
    )


    redirect_to @session.url, allow_other_host: true
  end

  def complete
    @order = Order.find(params[:order_id])

    if @cart.order_products[0]
      Stripe.api_key = 'sk_test_51M8YIsImcZ7reNdWFyYDqUvNZFyi2eshDo1EInzxlOhqPO7JDomzCRLLHwcvzGaHX6LuPLuMnAtsNVVuvBbU8ld500R9PEwXHf'
      @render_cart = false
      @complete_session = Stripe::Checkout::Session.retrieve(params[:session_id]);

      total = @complete_session.amount_total / 100;
      tax = total - @order.order_subtotal

      @order.update(
        order_total: total,
        order_tax_total: tax,
        order_state: "Paid",
      )

      @order.cart = @cart

      reset_session
    end
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/views/cart/_cart.html.erb
<%= turbo_frame_tag "cart" do%>
    <h2>Cart</h2>
    <% if @cart.order_products.count > 0 %>
    <%= render "cart/order_products" %>
    <p>Total: <%= @cart.total%> </p>
    <% else %>
    <p>Your Cart is Empty</p>
    <% end %>
<% end %>

app/views/cart/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :order_date, style: "display: block" %>
    <%= form.date_field :order_date %>
  </div>

  <div>
    <%= form.label :order_subtotal, style: "display: block" %>
    <%= form.text_field :order_subtotal %>
  </div>

  <div>
    <%= form.label :order_tax_rate, style: "display: block" %>
    <%= form.text_field :order_tax_rate %>
  </div>

  <div>
    <%= form.label :order_total, style: "display: block" %>
    <%= form.text_field :order_total %>
  </div>

  <div>
    <%= form.label :order_state, style: "display: block" %>
    <%= form.text_field :order_state %>
  </div>

  <div>
    <%= form.label :order_address, style: "display: block" %>
    <%= form.text_field :order_address %>
  </div>

  <div>
    <%= form.label :order_postal_code, style: "display: block" %>
    <%= form.text_field :order_postal_code %>
  </div>

  <div>
    <%= form.label :order_province, style: "display: block" %>
    <%= form.text_field :order_province %>
  </div>

  <div>
    <%= form.label :order_tracking_number, style: "display: block" %>
    <%= form.number_field :order_tracking_number %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cart/_order_products.html.erb
<% @cart.order_products.each do |order_product| %>
    <% product = order_product.custom_product %>
    <div id="<%= "cart-#{product.id}" %>">
    <div style="display:flex;justify-content:space-between;margin: 0em 5em;">
      <strong>Name:</strong>
      <%= product.product.name %>
      <strong>Description:</strong>
      <%= product.product.description %>
      <strong>Price:</strong>
      <%= product.price %>
      <%= form_with(url: cart_add_path) do |f|%>
        <%= select_tag :choice, options_for_select(Character.all.map { |character| [character.name.capitalize, character.id]}, order_product.custom_product.character_id)%>
        <%= f.hidden_field :order_product_id, value: order_product.id%>
        <%= f.hidden_field :id, value: product.product_id%>
        <%= f.number_field :quantity, value: order_product.quantity, min: 0 %>
        <%= f.submit "Update"%>
        <% end %>
      <%= form_with(url: cart_remove_path) do |f| %>
        <%= f.hidden_field :id, value: order_product.id %>
        <%= f.submit "Remove" %>
      <% end %>
      <strong>Total:</strong>
      <%= order_product.total %>
    </div>
  </div>
<% end %>

app/views/cart/_total.html.erb
<%= turbo_frame_tag "totals" do%>
    <% if @province %>
        <h3>Subtotal: $<%= @cart.total %></h3>
        <h3>PST: $<%= sprintf('%.2f', (@cart.total * @province.pst))  %></h3>
        <h3>GST: $<%= sprintf('%.2f', (@cart.total * @province.gst)) %></h3>
        <h3>HST: $<%= sprintf('%.2f', (@cart.total * @province.hst)) %></h3>
        <h3>Total: $<%= sprintf('%.2f', (@cart.total + (@cart.total * @province.pst) + (@cart.total * @province.gst) + (@cart.total * @province.hst))) %></h3>
    <% end %>
<% end %>

app/views/cart/complete.html.erb
<h1>Thank you for your Order!</h1>
<p>Status: <%= @order.order_state %></p>
<p>Sub-Total: <%= @order.order_subtotal %></p>
<p>Tax: <%= @order.order_tax_total %></p>
<p>Total: <%= @order.order_total %></p>
<h3>Items: </h3>
<% @order.cart.order_products.each do |product| %>
<div>
    <ul>
        <li>Name: <%= product.custom_product.product.name%></li>
        <li>Pokemon: <%= product.custom_product.character.name%></li>
        <li>Price: <%= product.price %></li>
        <li>Quantity: <%= product.quantity %></li>
        <li>Total: <%= product.total %></li>
    </ul>
</div>
<% end %>

app/views/cart/show.html.erb
<h1>Your Cart</h1>
<%= render "cart/order_products" %>
<p>Current Total: <%= @cart.total%> </p>
<% address_not_used = true %>

<%= form_with(url: cart_update_prices_path) do |form| %>
    <%= form.select 'tax_province', options_for_select(Province.all.map{|el| [el.name, el.id]}), :prompt => "Please Select a Province" %>
    <%= form.submit "Calculate Price"%>
<% end %>
<%= render "cart/total" %>
<% if @cart.order_products.count > 0 %>
    <% if customer_signed_in? %>
        <% if current_customer.address_id %>
        <h3>This order will use your saved address of:</h3>
        <p><%= current_user.address.line1 %></p>
        <p><%= current_user.address.city %></p>
        <p><%= current_user.address.province.name %></p>
        <p><%= current_user.address.postal_code %></p>
        <% address_not_used = false %>
        <% end %>
    <% end %>
    <% if address_not_used %>
        <h2>Please Enter your shipping address</h2>
        <%= form_tag cart_checkout_path, :method => "get", :data => {turbo: false} do |f| %>
            <%= select_tag 'province', options_for_select(Province.all.map{|el| [el.name, el.id]}), :prompt => "Please Select a Province" %>
            <br>
            <%= text_field_tag :line1, params[:line1], placeholder: "Street Address: 123 Example St" %>
            <%= text_field_tag :postal_code, params[:postal_code], placeholder: "Postal Code: A2A2A2", maxlength: 6 %>
            <%= text_field_tag :city, params[:city], placeholder: "City" %>
            <br>
            <%= submit_tag 'Checkout with Stripe' %>
        <% end %>
    <% end %>
<% end %>