config/routes.rb
Rails.application.routes.draw do
  devise_for :customers do
    get "/customers/sign_out" => "devise/sessions#destroy", :as => :destroy_customer_session
  end
  get 'home/About'
  get 'home/Contact'
  get 'cart' => 'cart#show'
  get 'cart/complete'
  post 'cart/add'
  post 'cart/remove'
  post 'cart/update_prices'
  get 'cart/checkout' => 'cart#checkout'
  post 'cart/checkout' => 'cart#checkout'
  get '/products/search'
  get 'categories' => 'categories#index'
  resources :categories
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # resources :characters
  resources :products
  # resources :shipments
   resources :orders
   resources :customers

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
end

app/models/address.rb
class Address < ApplicationRecord
  has_one :province
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :order_products
  has_many :custom_product, through: :order_products

  def total
    order_products.to_a.sum { |order_product| order_product.total }
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, uniqueness: true
end

app/models/character.rb
class Character < ApplicationRecord
  has_many :custom_products

  validates :name, uniqueness: true
end

app/models/custom_product.rb
class CustomProduct < ApplicationRecord
  belongs_to :product
  belongs_to :character
  has_many :order_products
  has_many :carts, through: :order_products

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
  has_one :address

end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  has_one :shipment
  has_one :cart
  has_one :address

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :custom_product
  belongs_to :cart

  def total
    custom_product.price * quantity
  end

  def in_cents
    (custom_product.price * 100).to_i
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :custom_products
  belongs_to :category

  paginates_per 10
end

app/models/province.rb
class Province < ApplicationRecord
end

app/models/shipment.rb
class Shipment < ApplicationRecord
  belongs_to :order

end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://js.stripe.com/v3/"></script>
    <title>PokePosh</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "cart/cart" if @render_cart %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <ul>
      <%= link_to "Cart", @cart %>
      <%= link_to "Products", products_path %>
      <%= link_to "Categories", categories_path %>
      <% if customer_signed_in? %>
      <% else %>
        <%= link_to "Sign In", new_customer_session_path %>
        <%= link_to "Register", new_customer_registration_path %>
      <% end %>
    </ul>

    <%= form_tag("/products/search", :method => "get") do%>
      <%= text_field_tag :search, params[:search], placeholder: "Search Categories (Leave blank for all items in category)" %> -->
      <%= select_tag 'category', options_for_select(Category.all.map{|el| [el.name, el.id]}), :prompt => "All Categories" %>
      <%= submit_tag 'Search' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_head.html.erb
>